
-- generate ninja files
local is_windows = package.config:sub(1,1) == "\\"
local lines = { "# AUTOGENERATED, GO EDIT THE BUILD.LUA" }

local ld = "ld.lld"
local host_exe = ""
if is_windows then
    ld = ld..".exe"
    host_exe = ".exe"
end

function rules(list)
    for i=1,#list do
        local name = list[i].name
        table.insert(lines, "rule "..name)
        for k,v in pairs(list[i]) do
            if k ~= "name" then
                table.insert(lines, "  "..k.." = "..v)
            end
        end
        table.insert(lines, "")
    end
end

function command(out, input, cmd, extra_input)
    if type(input) == "table" then
        input = table.concat(input, " ")
    end

    local line = "build "..out..": run "..input
    if extra_input ~= nil then
        line = line.." | "..extra_input
    end

    table.insert(lines, line)
    table.insert(lines, string.format("  cmd = %s", cmd:gsub("$in", input):gsub("$out", out)))
end

function build(name, cmd, input, content)
    if type(input) == "table" then
        input = table.concat(input, " ")
    end

    table.insert(lines, "build "..name..": "..cmd.." "..input)
    if content then
        for k,v in pairs(content) do
            table.insert(lines, "  "..k.." = "..v)
        end
    end
end


-- package freestanding headers into C file
function list_files(path, pat)
    local x = {}
    if is_windows then
        local cmd = io.popen("dir /B "..path:gsub("/", "\\")..pat)
        for c in cmd:lines() do
            x[#x + 1] = path..c
        end
        cmd:close()
    else
        local cmd = io.popen("find "..path..pat.." -maxdepth 1")
        for c in cmd:lines() do
            x[#x + 1] = c
        end
        cmd:close()
    end
    return x
end

function filename(file)
    return file:match("^.+/(.+)%..+")
end

local cflags     = " -std=gnu23 -g -Wall -I include -masm=intel -nostdlib -mno-red-zone -fno-stack-protector -fno-finite-loops -Wno-unused"
local elf_cflags = "-target x86_64-linux-gnu -ffreestanding "..cflags
local efi_cflags = "-target x86_64-pc-win32-coff -fno-PIC -fshort-wchar "..cflags

rules({
    {
        name = "cc",
        depfile = "$out.d",
        command = "clang  $in $flags -MD -MF $out.d -o $out",
        description = "CC $in"
    },
    {
        name = "ld",
        command = ld.." $in $flags -o $out",
        description = "LINK $out"
    },
    {
        name = "link",
        command = "lld-link $in $flags /out:$out",
        description = "LINK $out"
    },
    {
        name = "nasm",
        command = "nasm $in -f elf64 -o $out",
        description = "NASM $out"
    },
    {
        name = "run",
        command = "$cmd",
        description = "$cmd"
    }
})

-- InitRD
do
    local init_rd_list = {
        "userland/drivers.txt",
    }

    table.insert(lines, "# INIT PROGRAM")
    build("objs/init.elf", "cc", "userland/init/main.c", {
        flags = elf_cflags.." -fuse-ld=lld -T userland/init/link.ld -fpic"
    })

    table.insert(lines, "# INITRD")
    build("objs/bake_initrd"..host_exe, "cc", "userland/bake_initrd.c", { flags = "" })
    command("objs/initrd", init_rd_list, "objs/bake_initrd"..host_exe.." $out $in", "objs/bake_initrd"..host_exe)
    table.insert(lines, "")
end

-- Kernel
do
    table.insert(lines, "# KERNEL")
    table.insert(lines, "flags = -c -fPIC -fno-omit-frame-pointer -I src -DKERNEL_LAND "..elf_cflags)

    local objs = {}
    local asm_files = list_files("src/arch/x64/", "*.s")
    for i,f in ipairs(asm_files) do
        local obj_out = "objs/"..filename(f)..".s.o"
        build(obj_out, "nasm", f)
        table.insert(objs, obj_out)
    end

    local arch_files = list_files("src/arch/x64/", "*.c")
    for i,f in ipairs(arch_files) do
        local obj_out = "objs/"..filename(f)..".o"
        build(obj_out, "cc", f)
        table.insert(objs, obj_out)
    end

    local files = list_files("src/kernel/", "*.c")
    for i,f in ipairs(files) do
        local obj_out = "objs/"..filename(f)..".o"
        local input = f
        if f == "src/kernel/kernel.c" then
            input = input.." | objs/init.elf"
        end
        build(obj_out, "cc", input)
        table.insert(objs, obj_out)
    end

    build("objs/kernel.so", "ld", table.concat(objs, " ").." | src/kernel/link.ld", { flags="-T src/kernel/link.ld -nostdlib -pie" })
    table.insert(lines, "")
end

-- EFI Bootloader
do
    table.insert(lines, "# EFI BOOTLOADER")
    build("objs/efi.o", "cc", "src/boot/efi_main.c | objs/kernel.so objs/initrd", {
        flags = efi_cflags.." -c"
    })
    build("bin/efi/boot/bootx64.efi", "link", "objs/efi.o", {
        flags = "-subsystem:efi_application -nodefaultlib -dll -entry:efi_main"
    })
    table.insert(lines, "")
end

-- Export & run ninja file
ninja = io.open("build.ninja", "wb")
ninja:write(table.concat(lines, "\n"))
ninja:close()
local _0, _1, res = os.execute("ninja")
if res and res ~= 0 then os.exit(res) end

-- os.execute("cp bin/efi/boot/bootx64.efi C:/Users/yasse/OneDrive/Escritorio/PXE")
