port=0
interface=wlp5s0
dhcp-range=192.168.20.0,proxy

# ----- TFTP CONFIG -----
enable-tftp
tftp-root=/var/ftp
pxe-service=X86-64_EFI, "Boot!", bootx64.efi

# ----- ENABLE LOGGING -----
log-queries
log-dhcp
log-facility=/var/log/dnsmasq.log

